// Placeholder data for the Stock Movement Ledger page (spec §7.10). No
// backend endpoints exist yet for the ledger — this module is the single
// place to swap mocks for real calls against /api/v1/inventory/movements.
// The first 8 entries are the exact records already shown in the dashboard's
// "Recent Movements" widget (same movement numbers, types, quantities, and
// timestamps), extended here with the full ledger field set; 8 more entries
// round out coverage to all 16 movement types.

import type { MovementType } from "./dashboard-data";

export interface StockMovementEntry {
  id: string;
  movementNumber: string;
  type: MovementType;
  productName: string;
  sku: string;
  location: string;
  quantityBefore: number;
  quantityChange: number;
  quantityAfter: number;
  reservedBefore: number;
  reservedChange: number;
  reservedAfter: number;
  unitCost: number;
  referenceType: string;
  referenceNumber: string;
  reason: string;
  performedBy: string;
  approvedBy: string;
  occurredAt: string;
}

export const STOCK_MOVEMENTS: StockMovementEntry[] = [
  {
    id: "1",
    movementNumber: "SM-2026-004821",
    type: "PURCHASE_RECEIPT",
    productName: "Lumea Perfume - Inspired by BR540, 50 ml",
    sku: "LUM-BR540-50",
    location: "Main warehouse",
    quantityBefore: 1200,
    quantityChange: 240,
    quantityAfter: 1440,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 320,
    referenceType: "Goods Receipt",
    referenceNumber: "GR-2026-000050",
    reason: "Confirmed goods receipt against purchase order",
    performedBy: "R. Domingo",
    approvedBy: "",
    occurredAt: "2026-08-04T08:12:00Z",
  },
  {
    id: "2",
    movementNumber: "SM-2026-004820",
    type: "TRANSFER_OUT",
    productName: "Cotton Tote Bag - Natural",
    sku: "CTB-NAT-01",
    location: "Main warehouse",
    quantityBefore: 420,
    quantityChange: -60,
    quantityAfter: 360,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 60,
    referenceType: "Stock Transfer",
    referenceNumber: "ST-2026-000031",
    reason: "Stock transfer dispatched to branch warehouse",
    performedBy: "J. Alcantara",
    approvedBy: "",
    occurredAt: "2026-08-04T07:55:00Z",
  },
  {
    id: "3",
    movementNumber: "SM-2026-004819",
    type: "TRANSFER_IN",
    productName: "Cotton Tote Bag - Natural",
    sku: "CTB-NAT-01",
    location: "Branch warehouse",
    quantityBefore: 180,
    quantityChange: 60,
    quantityAfter: 240,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 60,
    referenceType: "Stock Transfer",
    referenceNumber: "ST-2026-000031",
    reason: "Stock transfer received from main warehouse",
    performedBy: "J. Alcantara",
    approvedBy: "",
    occurredAt: "2026-08-04T07:55:00Z",
  },
  {
    id: "4",
    movementNumber: "SM-2026-004818",
    type: "SALE_ISSUE",
    productName: "Ceramic Mug - Matte Black, 350 ml",
    sku: "CMG-BLK-350",
    location: "Retail branch",
    quantityBefore: 96,
    quantityChange: -18,
    quantityAfter: 78,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 85,
    referenceType: "Sales Order",
    referenceNumber: "SO-2026-008842",
    reason: "Point-of-sale integration sale",
    performedBy: "POS Integration",
    approvedBy: "",
    occurredAt: "2026-08-04T07:40:00Z",
  },
  {
    id: "5",
    movementNumber: "SM-2026-004817",
    type: "ADJUSTMENT_OUT",
    productName: "Scented Candle - Sandalwood, 200 g",
    sku: "SCN-SDW-200",
    location: "Damaged stock area",
    quantityBefore: 96,
    quantityChange: -12,
    quantityAfter: 84,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 110,
    referenceType: "Stock Adjustment",
    referenceNumber: "SA-2026-000063",
    reason: "Water damage during storage",
    performedBy: "M. Reyes",
    approvedBy: "L. Herrera (Approver)",
    occurredAt: "2026-08-04T07:05:00Z",
  },
  {
    id: "6",
    movementNumber: "SM-2026-004816",
    type: "COUNT_VARIANCE_IN",
    productName: "Bamboo Cutlery Set",
    sku: "BMB-CTL-04",
    location: "Store stockroom",
    quantityBefore: 62,
    quantityChange: 4,
    quantityAfter: 66,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 45,
    referenceType: "Stock Count",
    referenceNumber: "SC-2026-000021",
    reason: "Physical count found additional units",
    performedBy: "K. Santos",
    approvedBy: "L. Herrera (Approver)",
    occurredAt: "2026-08-04T06:48:00Z",
  },
  {
    id: "7",
    movementNumber: "SM-2026-004815",
    type: "MANUAL_ISSUE",
    productName: "Marketing Sample Kit",
    sku: "MKT-SMP-01",
    location: "Main warehouse",
    quantityBefore: 50,
    quantityChange: -25,
    quantityAfter: 25,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 15,
    referenceType: "Manual Issue",
    referenceNumber: "SI-2026-000014",
    reason: "Marketing sample kit distribution",
    performedBy: "R. Domingo",
    approvedBy: "",
    occurredAt: "2026-08-03T17:22:00Z",
  },
  {
    id: "8",
    movementNumber: "SM-2026-004814",
    type: "REVERSAL",
    productName: "Lumea Perfume - Inspired by BR540, 50 ml",
    sku: "LUM-BR540-50",
    location: "Main warehouse",
    quantityBefore: 1220,
    quantityChange: -10,
    quantityAfter: 1210,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 320,
    referenceType: "Stock Adjustment",
    referenceNumber: "SA-2026-000058",
    reason: "Correcting an over-posted adjustment from the prior week",
    performedBy: "R. Domingo",
    approvedBy: "L. Herrera (Approver)",
    occurredAt: "2026-08-03T16:10:00Z",
  },
  {
    id: "9",
    movementNumber: "SM-2026-004813",
    type: "OPENING_BALANCE",
    productName: "Herbal Tea Sampler - 12-Pack",
    sku: "HTS-SMP-12",
    location: "Store stockroom",
    quantityBefore: 0,
    quantityChange: 500,
    quantityAfter: 500,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 130,
    referenceType: "System Setup",
    referenceNumber: "MIGRATION-2026-INIT",
    reason: "Initial system stock load",
    performedBy: "System Migration",
    approvedBy: "",
    occurredAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "10",
    movementNumber: "SM-2026-004812",
    type: "RESERVATION",
    productName: "Ceramic Mug - Matte Black, 350 ml",
    sku: "CMG-BLK-350",
    location: "Retail branch",
    quantityBefore: 90,
    quantityChange: 0,
    quantityAfter: 90,
    reservedBefore: 15,
    reservedChange: 25,
    reservedAfter: 40,
    unitCost: 85,
    referenceType: "Sales Order",
    referenceNumber: "SO-2026-008810",
    reason: "Reserved for a pending sales order",
    performedBy: "K. Santos",
    approvedBy: "",
    occurredAt: "2026-08-03T09:00:00Z",
  },
  {
    id: "11",
    movementNumber: "SM-2026-004811",
    type: "RESERVATION_RELEASE",
    productName: "Ceramic Mug - Matte Black, 350 ml",
    sku: "CMG-BLK-350",
    location: "Retail branch",
    quantityBefore: 90,
    quantityChange: 0,
    quantityAfter: 90,
    reservedBefore: 40,
    reservedChange: -25,
    reservedAfter: 15,
    unitCost: 85,
    referenceType: "Sales Order",
    referenceNumber: "SO-2026-008810",
    reason: "Sales order cancelled, reservation released",
    performedBy: "K. Santos",
    approvedBy: "",
    occurredAt: "2026-08-03T15:00:00Z",
  },
  {
    id: "12",
    movementNumber: "SM-2026-004810",
    type: "SUPPLIER_RETURN",
    productName: "Brass Desk Organizer",
    sku: "BRS-DSK-02",
    location: "Main warehouse",
    quantityBefore: 60,
    quantityChange: -10,
    quantityAfter: 50,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 210,
    referenceType: "Purchase Order",
    referenceNumber: "PO-2026-000098",
    reason: "Defective units returned to supplier",
    performedBy: "R. Domingo",
    approvedBy: "",
    occurredAt: "2026-08-02T14:00:00Z",
  },
  {
    id: "13",
    movementNumber: "SM-2026-004809",
    type: "ADJUSTMENT_IN",
    productName: "Aromatherapy Oil - Lavender, 30 ml",
    sku: "ARO-LAV-30",
    location: "Main warehouse",
    quantityBefore: 114,
    quantityChange: 6,
    quantityAfter: 120,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 95,
    referenceType: "Stock Adjustment",
    referenceNumber: "SA-2026-000064",
    reason: "Physical count found additional units",
    performedBy: "M. Reyes",
    approvedBy: "L. Herrera (Approver)",
    occurredAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "14",
    movementNumber: "SM-2026-004808",
    type: "MANUAL_RECEIPT",
    productName: "Wool Throw Blanket - Grey",
    sku: "WTB-GRY-01",
    location: "Branch warehouse",
    quantityBefore: 5,
    quantityChange: 15,
    quantityAfter: 20,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 380,
    referenceType: "Manual Receipt",
    referenceNumber: "MR-2026-000009",
    reason: "Manual receipt outside the standard PO workflow",
    performedBy: "R. Domingo",
    approvedBy: "",
    occurredAt: "2026-07-30T11:00:00Z",
  },
  {
    id: "15",
    movementNumber: "SM-2026-004807",
    type: "CUSTOMER_RETURN",
    productName: "Scented Candle - Lavender, 200 g",
    sku: "SCN-LAV-200",
    location: "Retail branch",
    quantityBefore: 15,
    quantityChange: 3,
    quantityAfter: 18,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 110,
    referenceType: "Sales Order",
    referenceNumber: "SO-2026-008790",
    reason: "Customer returned an unopened item",
    performedBy: "K. Santos",
    approvedBy: "",
    occurredAt: "2026-07-29T16:00:00Z",
  },
  {
    id: "16",
    movementNumber: "SM-2026-004806",
    type: "COUNT_VARIANCE_OUT",
    productName: "Herbal Tea Sampler - 12-Pack",
    sku: "HTS-SMP-12",
    location: "Store stockroom",
    quantityBefore: 210,
    quantityChange: -8,
    quantityAfter: 202,
    reservedBefore: 0,
    reservedChange: 0,
    reservedAfter: 0,
    unitCost: 130,
    referenceType: "Stock Count",
    referenceNumber: "SC-2026-000021",
    reason: "Physical count came up short",
    performedBy: "K. Santos",
    approvedBy: "L. Herrera (Approver)",
    occurredAt: "2026-07-29T10:15:00Z",
  },
];

export function getStockMovements(): StockMovementEntry[] {
  return STOCK_MOVEMENTS;
}
